import "../src/styles/modern-normalize.css";
import "../src/styles/style.css";
import "../src/styles/desktop-navbar.css";
import "../src/styles/mobile-navbar.css";
import "../src/styles/mediaquery.css";
import "../src/styles/hero.css";
import "../src/styles/ide.css";
import "../src/styles/colors.css";
import "../src/styles/about-me.css";
